### ISSUE TITLE
Content  writing issues...

### ISSUE THREAD

**Issue by aamick** [publicservantsprayer/repsp#5]
These issues are not as important as most people won't see these but they are kind of a pain.

1. you can only highlight in the PC version
2. even if you return after writing a line, if there is no space between it and the next line you write, it will be on the same line, however if you do put a space between the writing then there appears a space...making it impossible to write something on the next line down without it first starting on the line above.

**Comment by namick** [comment]
1. This is a feature of Chrome's Mobile view.  Because phones do not have mouse pointers, Chrome simulates that by not letting you use it in that view.  You can however, turn off the mobile view and shrink the browser width (expanding dev tools) to simulate the view and still have mouse editing ability.

2. This is how the Markdown parser works converting a blank line to new paragraph tags.  Without a blank line, it will be in the same paragraph tag which will ignore newlines when rendered in a browser.  You can work around this if you want start a new line but stay in the same paragraph by inserting a `<br />` tag in the markdown like i'm about to do right here.  <br />Markdown will render the break properly without creating a new paragraph.
